# Generated by Django 5.0.6 on 2024-05-13 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedpageapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table='comments_db',
        ),
    ]
